### PR TITLE
[WIP] Test harness v2

### PR DESCRIPTION
**Pull request by sharwell**
With this pull request, integration tests marked with `[IdeFact]` run directly inside Visual Studio rather than running in a separate process. The attribute supports limits on the versions of Visual Studio supported by a specific test. Here is an example of some tests that can be written this way:

https://github.com/tunnelvisionlabs/MouseFastScroll/blob/a9a0c155e69e61972cbbc28fec6733fc77e06860/Tvl.VisualStudio.MouseFastScroll.IntegrationTests/IdeFactTest.cs#L26-L58

Here's what the above tests look like in Test Explorer in Visual Studio 2017:

image

### CODE REVIEW

**Comment by sharwell** [comment]
@jcansdale This pull request is intended to take the concept of #19 and generalize it to tremendously expand the capability of integration tests.

**Comment by jcansdale** [comment]
@sharwell, thanks for the heads up. I look forward to giving it a spin!

Something that I'm keen to have it the ability to reuse experimental `devenv.exe` instances between test runs. That would make it so much quicker to iterate on tests!

This would involve loading the tests using `Assembly.Load(byte[], byte[])` rather than `Assembly.LoadFrom(file)` (so we don't end up locking the test assembly/pdb). Is this something you'd be up for supporting?

**Comment by sharwell** [comment]
Some known remaining items:

* Category (trait) filters passed to the command line runner seem to be ignored by the new framework
* Something is throwing an ObjectDisposedException at the end of the last IDE treat
* Switching from IdeFact (new) to WpfFact (legacy) doesn't close the Visual Studio instance used by the new test
* Consider providing a standard `JoinableTaskContext`
* Need to implement state cleanup between tests. This should ideally be extensible.
* Cancellation relies on messages currently. It should be updated to push the cancellation to the remote process.

**Comment by sharwell** [comment]
Closing in favor of #25

**Pull request closed without merging**
